version: '2.1'

services:
  backend-api2:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/rpe/backend-api2
    ports:
      - $SERVER_PORT:$SERVER_PORT
