apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rpe-backend-api2 App
name: rpe-backend-api2
home: https://github.com/hmcts/rpe-backend-api2
version: 0.0.1
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 3.0.2
    repository: '@hmctspublic'
